binary_sensor:

- platform: template
  sensors:
    motion_indkorelse:
      friendly_name: Camera Indkorelse
      device_class: motion
      entity_id: camera.indkorelse
      value_template: "{{ is_state('camera.indkorelse', 'motion') }}"
      delay_off: 
          seconds: 30
