binary_sensor:
#   - platform: mqtt
#     state_topic: dummy/floorplan/sensor
#     name: Floorplan

  - platform: iss
    # show_on_map: true ##This makes the ISS show on Home Assistant map
    