switch:

- platform: template
  switches:
      camera_indkorelse_email:
        value_template: "{{ is_state_attr('camera.indkorelse', 'email_enabled', true) }}"
        turn_on:
          service: camera.enable_email
          data:
            entity_id: camera.indkorelse
        turn_off:
          service: camera.disable_email
          data:
            entity_id: camera.indkorelse
        icon_template: >-
          {% if is_state_attr('camera.indkorelse', 'email_enabled', true) %}
            mdi:email
          {% else %}
            mdi:email-outline
          {% endif %}
            
      camera_indkorelse_ftp:
        value_template: "{{ is_state_attr('camera.indkorelse', 'ftp_enabled', true) }}"
        turn_on:
          service: camera.enable_ftp
          data:
            entity_id: camera.indkorelse
        turn_off:
          service: camera.disable_ftp
          data:
            entity_id: camera.indkorelse
        icon_template: >-
          {% if is_state_attr('camera.indkorelse', 'ftp_enabled', true) %}
            mdi:filmstrip
          {% else %}
            mdi:filmstrip-off
          {% endif %}
          
      camera_indkorelse_ir_lights:
        value_template: "{{ is_state_attr('camera.indkorelse', 'ir_lights_enabled', true) }}"
        turn_on:
          service: camera.enable_ir_lights
          data:
            entity_id: camera.indkorelse
        turn_off:
          service: camera.disable_ir_lights
          data:
            entity_id: camera.indkorelse
        icon_template: >-
          {% if is_state_attr('camera.indkorelse', 'ir_lights_enabled', true) %}
            mdi:flashlight
          {% else %}
            mdi:flashlight-off
          {% endif %}

      camera_indkorelse_motion_detection:
        value_template: "{{ is_state_attr('camera.indkorelse', 'motion_detection_enabled', true) }}"
        turn_on:
          service: camera.enable_motion_detection
          data:
            entity_id: camera.indkorelse
        turn_off:
          service: camera.disable_motion_detection
          data:
            entity_id: camera.indkorelse
        icon_template: >-
          {% if is_state_attr('camera.indkorelse', 'motion_detection_enabled', true) %}
            mdi:motion-sensor
          {% else %}
            mdi:motion-sensor-off
          {% endif %}
