- id: '1608431495586'
  alias: Motion-activated Light
  description: driveway
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      no_motion_wait: '180'
      motion_entity: binary_sensor.driveway_motion
      light_target:
        area_id: 02c1ee50a89a43aba8641e93ca2fc403
