
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
  
homeassistant:
  packages: !include_dir_named packages

group: !include groups.yaml
automation: !include automations.yaml
automation automationDirectory: !include_dir_list automations/
script: !include scripts.yaml
scene sceneUI: !include scenes.yaml
scene: !include scene.yaml
sensor: !include sensor.yaml

# #Lille WC
# climate wavinAhc9000_1:
#   - platform: mqtt
#     name: LilleWCFordoerVarme
#     current_temperature_topic: "heat/floor807D3A790941/0/current"
#     temperature_command_topic: "heat/floor807D3A790941/0/target_set"
#     temperature_state_topic: "heat/floor807D3A790941/0/target"
#     mode_command_topic: "heat/floor807D3A790941/0/mode_set"
#     mode_state_topic: "heat/floor807D3A790941/0/mode"
#     modes:
#     - "heat"
#     - "off"
#     availability_topic: "heat/floor807D3A790941/online"
#     payload_available: "True"
#     payload_not_available: "False"
#     qos: 0

# sensor wavinBattery1:
#   - platform: mqtt
#     state_topic: "heat/floor807D3A790941/0/battery"
#     availability_topic: "heat/floor807D3A790941/online"
#     payload_available: "True"
#     payload_not_available: "False"
#     name: LilleWCBatt
#     unit_of_measurement: "%"
#     device_class: battery
#     qos: 0

# #Bryggers
# climate wavinAhc9000_2:
#   - platform: mqtt
#     name: BryggersVarme
#     current_temperature_topic: "heat/floor807D3A790941/1/current"
#     temperature_command_topic: "heat/floor807D3A790941/1/target_set"
#     temperature_state_topic: "heat/floor807D3A790941/1/target"
#     mode_command_topic: "heat/floor807D3A790941/1/mode_set"
#     mode_state_topic: "heat/floor807D3A790941/1/mode"
#     modes:
#     - "heat"
#     - "off"
#     availability_topic: "heat/floor807D3A790941/online"
#     payload_available: "True"
#     payload_not_available: "False"
#     qos: 0

# sensor wavinBattery2:
#   - platform: mqtt
#     state_topic: "heat/floor807D3A790941/1/battery"
#     availability_topic: "heat/floor807D3A790941/online"
#     payload_available: "True"
#     payload_not_available: "False"
#     name: BryggersBatt
#     unit_of_measurement: "%"
#     device_class: battery
#     qos: 0

# #Køkken
# climate wavinAhc9000_3:
#   - platform: mqtt
#     name: KøkkenVarme
#     current_temperature_topic: "heat/floor807D3A790941/2/current"
#     temperature_command_topic: "heat/floor807D3A790941/2/target_set"
#     temperature_state_topic: "heat/floor807D3A790941/2/target"
#     mode_command_topic: "heat/floor807D3A790941/2/mode_set"
#     mode_state_topic: "heat/floor807D3A790941/2/mode"
#     modes:
#     - "heat"
#     - "off"
#     availability_topic: "heat/floor807D3A790941/online"
#     payload_available: "True"
#     payload_not_available: "False"
#     qos: 0

# sensor wavinBattery3:
#   - platform: mqtt
#     state_topic: "heat/floor807D3A790941/2/battery"
#     availability_topic: "heat/floor807D3A790941/online"
#     payload_available: "True"
#     payload_not_available: "False"
#     name: KøkkenBatt
#     unit_of_measurement: "%"
#     device_class: battery
#     qos: 0

# #Stor WC
# climate wavinAhc9000_4:
#   - platform: mqtt
#     name: StorWCVarme
#     current_temperature_topic: "heat/floor807D3A790941/3/current"
#     temperature_command_topic: "heat/floor807D3A790941/3/target_set"
#     temperature_state_topic: "heat/floor807D3A790941/3/target"
#     mode_command_topic: "heat/floor807D3A790941/3/mode_set"
#     mode_state_topic: "heat/floor807D3A790941/3/mode"
#     modes:
#     - "heat"
#     - "off"
#     availability_topic: "heat/floor807D3A790941/online"
#     payload_available: "True"
#     payload_not_available: "False"
#     qos: 0

# sensor wavinBattery4:
#   - platform: mqtt
#     state_topic: "heat/floor807D3A790941/3/battery"
#     availability_topic: "heat/floor807D3A790941/online"
#     payload_available: "True"
#     payload_not_available: "False"
#     name: StorWCBatt
#     unit_of_measurement: "%"
#     device_class: battery
#     qos: 0

# #Gang
# climate wavinAhc9000_5:
#   - platform: mqtt
#     name: GangVarme
#     current_temperature_topic: "heat/floor807D3A790941/4/current"
#     temperature_command_topic: "heat/floor807D3A790941/4/target_set"
#     temperature_state_topic: "heat/floor807D3A790941/4/target"
#     mode_command_topic: "heat/floor807D3A790941/4/mode_set"
#     mode_state_topic: "heat/floor807D3A790941/4/mode"
#     modes:
#     - "heat"
#     - "off"
#     availability_topic: "heat/floor807D3A790941/online"
#     payload_available: "True"
#     payload_not_available: "False"
#     qos: 0

# sensor wavinBattery5:
#   - platform: mqtt
#     state_topic: "heat/floor807D3A790941/4/battery"
#     availability_topic: "heat/floor807D3A790941/online"
#     payload_available: "True"
#     payload_not_available: "False"
#     name: GangBatt
#     unit_of_measurement: "%"
#     device_class: battery
#     qos: 0

# #Tristans Værelse
# climate wavinAhc9000_6:
#   - platform: mqtt
#     name: TristansVarme
#     current_temperature_topic: "heat/floor807D3A790941/5/current"
#     temperature_command_topic: "heat/floor807D3A790941/5/target_set"
#     temperature_state_topic: "heat/floor807D3A790941/5/target"
#     mode_command_topic: "heat/floor807D3A790941/5/mode_set"
#     mode_state_topic: "heat/floor807D3A790941/5/mode"
#     modes:
#     - "heat"
#     - "off"
#     availability_topic: "heat/floor807D3A790941/online"
#     payload_available: "True"
#     payload_not_available: "False"
#     qos: 0

# sensor wavinBattery6:
#   - platform: mqtt
#     state_topic: "heat/floor807D3A790941/5/battery"
#     availability_topic: "heat/floor807D3A790941/online"
#     payload_available: "True"
#     payload_not_available: "False"
#     name: TristansBatt
#     unit_of_measurement: "%"
#     device_class: battery
#     qos: 0