id: '1588629574285'
alias: Vaskemaskine Notify when washer finnish
description: ''
trigger:
- entity_id: binary_sensor.vaskemaskine_wash_completed
  from: 'off'
  platform: state
  to: 'on'
condition: []
action:
- data:
    message: Vaskemaskinen er færdig.... tøm den!!!
  service: notify.mobile_app_sm_g988b
- data:
    message: Vaskemaskinen er færdig, tøm den trine haha :-D
  service: notify.mobile_app_sm_g986b