alias: 'gang On'
id: gangOn
initial_state: 'on'
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: tradfri_remote_gang
    event: 1002
action:
  service: light.toggle
  entity_id: light.gang_group