alias: 'gang Off'
id: gangOff
initial_state: 'on'
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: light.gang_group
    event: 5002
action:
  service: light.turn_off
  entity_id: light.gang_group