alias: Gang Turn on gang light when there is movement at nighttime
id: Gang_turn_on_gang_light_when_there_is_movement_at_nighttime
trigger:
  platform: state
  entity_id: binary_sensor.sensor_gang_philips
  to: 'on'
condition:
- condition: state
  entity_id: sun.sun
  state: 'below_horizon'
action:
  service: scene.turn_on
  entity_id: scene.GangNat