alias: Gang turn off gang light after 1 minute
id: 'Gang_turn_of_gang_light_after_1_minute'
description: ''
trigger:
- entity_id: binary_sensor.sensor_gang_philips
  from: 'on'
  platform: state
  to: 'off'
condition: []
action:
# - delay: 00:00:30 # don't know why, but hue motion sensor defaults to 1 minute "on" state, so the delay is not needed
- data: {}
  entity_id: light.gang_group
  service: light.turn_off