alias: 'Koekken allKoekkenOff'
id: allKoekkenOff
initial_state: 'on'
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: tradfri_remote_spisebord
    event: 5001
action:
  service: light.turn_off
  entity_id: 
    - light.spisebord
    - light.koekken1
    - light.koekken2