alias: 'Koekken allKoekkenOn'
id: allKoekkenOn
initial_state: 'on'
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: tradfri_remote_spisebord
    event: 1001
action:
  service: light.turn_on
  entity_id: 
    - light.spisebord
    - light.koekken1
    - light.koekken2