alias: 'koekken spisebord decrease brightness of spisebord from dimmer'
id: decrease_brightness_of_spisebord_from_dimmer
initial_state: 'on'
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: tradfri_remote_spisebord
    event: 3002
action:
  - service: light.turn_on
    data_template:
      entity_id: light.spisebord
      brightness: >
        {% set bri = state_attr('light.spisebord', 'brightness') | int %}
        {{ [bri-30, 0] | max }}