alias: ' koekken spisebord increase brightness of spisebord from dimmer'
id: increase_brightness_of_spisebord_from_dimmer
initial_state: 'on'
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: tradfri_remote_spisebord
    event: 2002
action:
  - service: light.turn_on
    data_template:
      entity_id: light.spisebord_lys
      brightness: >
        {% set bri = state_attr('light.spisebord_lys', 'brightness') | int %}
        {{ [bri+30, 249] | min }}