alias: 'koekken spisebord Off'
id: spisebordOff
initial_state: 'on'
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: tradfri_remote_spisebord
    event: 5002
action:
  service: light.turn_off
  entity_id: light.spisebord_lys