alias: 'koekken spisebord On'
id: spisebordOn
initial_state: 'on'
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: tradfri_remote_spisebord
    event: 1002
action:
  service: light.turn_on
  entity_id: light.spisebord