id: 'Turn_on_coffemaker_when_alarm_is_disabled'
alias: kaffemaskine turn on coffemaker when alarm is disabled
description: ''
trigger:
- entity_id: alarm_control_panel.aeblevangen_alarm
  from: armed
  platform: state
  to: disarmed
condition: []
action:
- data: {}
  entity_id: switch.kaffemaskine
  service: switch.turn_on