alias:  Koekken under_koekkenbordet On
id: under_koekkenbordet-On
trigger:
  platform: sun
  event: sunset
  offset: "-00:30:00"
action:
  service: light.turn_on
  entity_id: light.under_koekkenbordet