id: 'Trine is home'
alias: trine mobile notify when Trine returns home
description: ''
trigger:
- entity_id: person.trine
  from: 'not_home'
  platform: state
  to: 'home'
condition: []
action:
- data:
    message: Trine er hjemme!!!
  service: notify.mobile_app_trinesm_g986b
