alias: 'kontor Toggle'
id: kontorlys
initial_state: 'on'
trigger:
  platform: event
  event_type: deconz_event
  event_data:
    id: tradfri_remote_kontor
    event: 1002
action:
  service: switch.toggle
  entity_id: switch.sonoff_1000319a9b