id: Kontor_turn_on_heating_in_office
alias: Kontor turn on heating in office
description: turn off heating in office when window closes
trigger:
- entity_id: binary_sensor.kontor
  from: 'on'
  platform: state
  to: 'off'
condition: []
action:
- data:
    hvac_mode: auto
  entity_id: climate.kontor
  service: climate.set_hvac_mode