id: 'legestue_turn_on_heating_in_legestue'
alias: Legestue turn on heating in legestue
description: turn off heating in legestue when window closes
trigger:
- entity_id: binary_sensor.terrassedor_baghave, binary_sensor.terrassedor_forhave
  from: 'on'
  platform: state
  to: 'off'
condition: []
action:
- data:
    hvac_mode: auto
  entity_id: climate.lege_stue
  service: climate.set_hvac_mode