id: 'stue_turn_on_heating_in_stue'
alias: stue turn on heating in stue
description: turn off heating in office when window closes
trigger:
- entity_id: binary_sensor.stor_terrassedor
  from: 'on'
  platform: state
  to: 'off'
condition: []
action:
- data:
    hvac_mode: auto
  entity_id: climate.stue
  service: climate.set_hvac_mode