alias: legestue baghave terrassedørAabnerTTS
id: baghaveTerrassedørAabnerTTS
trigger:
- platform: state
  entity_id: binary_sensor.terrassedor_baghave
  to: 'on'
action:
- service: media_player.volume_set
  data_template:
    entity_id:
    # - media_player.google_home
    - media_player.kokken
    volume_level: '0.9'
- service: tts.google_cloud_say
  data:
    entity_id:
    # - media_player.google_home
    - media_player.kokken
    message: '..... Terrassedøren til baghaven er blevet åbnet! '
    cache: true