alias: kontor KontorVindueAabnerTTS
id: kontorVindueAabnerTTS
trigger:
  - platform: state
    entity_id: binary_sensor.kontor
    to: 'on'
action:
  - service: media_player.volume_set
    data_template:
      entity_id:
      # - media_player.google_home
      - media_player.kokken
      volume_level: '0.7'
  # - service: tts.google_cloud_say
  - service: tts.google_cloud_say
    data:
      entity_id: 
      # - media_player.google_home
      - media_player.kokken
      message: "..... Vinduet på kontoret er blevet åbnet! "
      cache: true