alias: Victoria Vindue1AabnerTTS
id: VictoriaVindue1AabnerTTS
trigger:
  - platform: state
    entity_id: binary_sensor.sophievindue1
    to: 'on'
action:
  - service: media_player.volume_set
    data_template:
      entity_id:
      # - media_player.google_home
      - media_player.kokken
      volume_level: '0.9'
  # - service: tts.google_cloud_say
  - service: tts.google_cloud_say
    data:
      entity_id: 
      # - media_player.google_home
      - media_player.kokken
      message: "..... Vinduet på Sophies værelse er blevet åbnet! "
      cache: true