alias: stue media player playing
id: Media_player_playing
trigger:
- platform: state
  entity_id: media_player.chromecast_ultra
  to: playing
  from: idle
condition:
- condition: state
  entity_id: sun.sun
  state: below_horizon
action:
  service: scene.turn_on
  entity_id: scene.livingroom_dim