alias: stue media player paused/stopped
id: Media_player_pausedstopped
trigger:
- platform: state
  entity_id: media_player.chromecast_ultra
  from: playing
  to: idle
condition:
- condition: state
  entity_id: sun.sun
  state: below_horizon
action:
  service: scene.turn_on
  entity_id: scene.livingroom_normal